---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys an Ethereum cluster on an existing VPC.

Parameters:
  VPCID:
    Type: AWS::EC2::VPC::Id
  NetworkSubnetIDs:
    Type: List<AWS::EC2::Subnet::Id>
  ALBSubnetIDs:
    Type: List<AWS::EC2::Subnet::Id>
  NumberOfEthereumClients:
    Type: Number
  NumberOfEthereumMiners:
    Type: Number
  InitialAccountAddresses:
    Type: String
  MinerAccountAddress:
    Type: String
  NetworkID:
    Type: Number
  InitialBlockGasLimit:
    Type: Number
  BlockGasLimit:
    Type: Number
  EC2InstanceProfileArn:
    Type: String
  EC2KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  ECSRoleForALB:
    Type: String
  NumberOfEC2Instances:
    Type: Number
  EC2InstanceType:
    Type: String
  NestedTemplateOrigin:
    Type: String
  RootStackName:
    Type: String
  EthereumNodeLogLevel:
    Type: String
  RunEthStats:
    Type: String
  EthStatsSecret:
    Type: String
  GasPriceFloor:
    Type: Number
  RunEthExplorer:
    Type: String
  ClusterName:
    Type: String
  InitialDifficulty:
    Type: Number
  EthereumDockerImage:
    Type: String
  EthStatsDockerImage:
    Type: String
  EthExplorerDockerImage:
    Type: String
  InitialAccountBalance:
    Type: Number
  ContainerPlatform:
    Type: String
  DockerRegion:
    Type: String
  DockerECRAccount:
    Type: String

Conditions:
  IsECSPlatform:
    Fn::Equals:
      - Ref: ContainerPlatform
      - "ecs"
  IsDockerLocal:
    Fn::Equals:
      - Ref: ContainerPlatform
      - "docker-local"
  IsRunningEthExplorer:
    Fn::Equals:
      - Ref: RunEthExplorer
      - "true"
  IsRunningEthStats:
    Fn::Equals:
      - Ref: RunEthStats
      - "true"

Resources:
  DockerLocalStack:
    Type: AWS::CloudFormation::Stack
    Condition: IsDockerLocal
    Properties:
      TemplateURL: !Sub "${NestedTemplateOrigin}ethereum-docker-local.template.yaml"
      Parameters:
        NestedTemplateOrigin:
          Ref: NestedTemplateOrigin
        RootStackName:
          Ref: RootStackName
        NetworkSubnetIDs:
          Fn::Join:
            - ","
            - Ref: NetworkSubnetIDs
        EC2KeyPairName:
          Ref: EC2KeyPairName
        EC2SecurityGroup:
          Ref: EC2SecurityGroup
        EC2InstanceProfileArn:
          Ref: EC2InstanceProfileArn
        EC2InstanceType:
          Ref: EC2InstanceType
        NetworkID:
          Ref: NetworkID
        RunEthExplorer:
          Ref: RunEthExplorer
        RunEthStats:
          Ref: RunEthStats
        EthereumDockerImage:
          Ref: EthereumDockerImage
        EthStatsDockerImage:
          Ref: EthStatsDockerImage
        EthExplorerDockerImage:
          Ref: EthExplorerDockerImage
        DockerRegion:
          Ref: DockerRegion
        DockerECRAccount:
          Ref: DockerECRAccount
        InitialDifficulty:
          Ref: InitialDifficulty
        EthereumNodeLogLevel:
          Ref: EthereumNodeLogLevel
        MinerAccountAddress:
          Ref: MinerAccountAddress
        InitialAccountAddresses:
          Ref: InitialAccountAddresses
        InitialBlockGasLimit:
          Ref: InitialBlockGasLimit
        BlockGasLimit:
          Ref: BlockGasLimit
        InitialAccountBalance:
          Ref: InitialAccountBalance
        GasPriceFloor:
          Ref: GasPriceFloor
        EthStatsSecret:
          Ref: EthStatsSecret

  EthereumECSStack:
    Type: AWS::CloudFormation::Stack
    Condition: IsECSPlatform
    Properties:
      TemplateURL: !Sub "${NestedTemplateOrigin}ethereum-ecs.template.yaml"
      Parameters:
        VPCID:
          Ref: VPCID
        NetworkSubnetIDs:
          Fn::Join:
            - ","
            - Ref: NetworkSubnetIDs
        ALBSubnetIDs:
          Fn::Join:
            - ","
            - Ref: ALBSubnetIDs
        NestedTemplateOrigin:
          Ref: NestedTemplateOrigin
        EC2InstanceProfileArn:
          Ref: EC2InstanceProfileArn
        NumberOfEthereumClients:
          Ref: NumberOfEthereumClients
        NumberOfEthereumMiners:
          Ref: NumberOfEthereumMiners
        InitialAccountAddresses:
          Ref: InitialAccountAddresses
        MinerAccountAddress:
          Ref: MinerAccountAddress
        ClusterName:
          Ref: ClusterName
        NetworkID:
          Ref: NetworkID
        InitialDifficulty:
          Ref: InitialDifficulty
        InitialBlockGasLimit:
          Ref: InitialBlockGasLimit
        BlockGasLimit:
          Ref: BlockGasLimit
        GasPriceFloor:
          Ref: GasPriceFloor
        EC2KeyPairName:
          Ref: EC2KeyPairName
        EC2SecurityGroup:
          Ref: EC2SecurityGroup
        ECSRoleForALB:
          Ref: ECSRoleForALB
        NumberOfEC2Instances:
          Ref: NumberOfEC2Instances
        EC2InstanceType:
          Ref: EC2InstanceType
        EthereumNodeLogLevel:
          Ref: EthereumNodeLogLevel
        EthStatsSecret:
          Ref: EthStatsSecret
        RootStackName:
          Ref: RootStackName
        RunEthExplorer:
          Ref: RunEthExplorer
        RunEthStats:
          Ref: RunEthStats
        EthereumDockerImage:
          Ref: EthereumDockerImage
        EthStatsDockerImage:
          Ref: EthStatsDockerImage
        EthExplorerDockerImage:
          Ref: EthExplorerDockerImage
        InitialAccountBalance:
          Ref: InitialAccountBalance
        LoadBalancerSecurityGroup:
          Ref: LoadBalancerSecurityGroup

Outputs:
  EthStatsURL:
    Value:
      Fn::If:
        - IsRunningEthStats
        - Fn::If:
          - IsECSPlatform
          - !Sub "http://${EthereumECSStack.Outputs.LoadBalancerDNSName}"
          - "Check EC2 Console"
        - "N/A"
  EthExplorerURL:
    Value:
      Fn::If:
        - IsRunningEthExplorer
        - Fn::If:
          - IsECSPlatform
          - !Sub "http://${EthereumECSStack.Outputs.LoadBalancerDNSName}:8080"
          - "Check EC2 Console"
        - "N/A"
  EthJsonRPCURL:
    Value:
      Fn::If:
        - IsECSPlatform
        - !Sub "http://${EthereumECSStack.Outputs.LoadBalancerDNSName}:8545"
        - "Check EC2 Console"
