---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an AutoScalingGroup of EC2 Instances

Parameters:
  NetworkSubnetIDs:
    Type: List<AWS::EC2::Subnet::Id>
  EC2InstanceProfileArn:
    Type: String
  EC2KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  NumberOfEC2Instances:
    Type: Number
  EC2InstanceType:
    Type: String
  InstanceAMICode:
    Type: String
    AllowedValues:
      - AMZNECSOPTIMIZEDAMI
      - AMZNEC2AMI
  InstanceNames:
    Type: String
  LaunchScriptText:
    Type: String

Mappings:
  AWSAMIRegionMap:
    AMI:
      AMZNECSOPTIMIZEDAMI: amzn-ami-2017.09.k-amazon-ecs-optimized
      AMZNEC2AMI: amzn-ami-hvm-2017.09.1.20180307-x86_64-gp2
    ap-northeast-1:
      AMZNECSOPTIMIZEDAMI: ami-5add893c
      AMZNEC2AMI: ami-a77c30c1
    ap-northeast-2:
      AMZNECSOPTIMIZEDAMI: ami-ba74d8d4
      AMZNEC2AMI: ami-5e1ab730
    ap-south-1:
      AMZNECSOPTIMIZEDAMI: ami-2149114e
      AMZNEC2AMI: ami-7c87d913
    ap-southeast-1:
      AMZNECSOPTIMIZEDAMI: ami-acbcefd0
      AMZNEC2AMI: ami-e2adf99e
    ap-southeast-2:
      AMZNECSOPTIMIZEDAMI: ami-4cc5072e
      AMZNEC2AMI: ami-43874721
    ca-central-1:
      AMZNECSOPTIMIZEDAMI: ami-a535b2c1
      AMZNEC2AMI: ami-5b55d23f
    eu-central-1:
      AMZNECSOPTIMIZEDAMI: ami-ac055447
      AMZNEC2AMI: ami-ac442ac3
    eu-west-1:
      AMZNECSOPTIMIZEDAMI: ami-bfb5fec6
      AMZNEC2AMI: ami-3bfab942
    eu-west-2:
      AMZNECSOPTIMIZEDAMI: ami-a48d6bc3
      AMZNEC2AMI: ami-dff017b8
    eu-west-3:
      AMZNECSOPTIMIZEDAMI: ami-914afcec
    sa-east-1:
      AMZNECSOPTIMIZEDAMI: ami-d3bce9bf
      AMZNEC2AMI: ami-5339733f
    us-east-1:
      AMZNECSOPTIMIZEDAMI: ami-cb17d8b6
      AMZNEC2AMI: ami-1853ac65
    us-east-2:
      AMZNECSOPTIMIZEDAMI: ami-1b90a67e
      AMZNEC2AMI: ami-25615740
    us-west-1:
      AMZNECSOPTIMIZEDAMI: ami-9cbbaffc
      AMZNEC2AMI: ami-bf5540df
    us-west-2:
      AMZNECSOPTIMIZEDAMI: ami-05b5277d
      AMZNEC2AMI: ami-d874e0a0

Resources:

  ServiceAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        Ref: NetworkSubnetIDs
      LaunchConfigurationName:
        Ref: ContainerInstances
      MinSize: '1'
      MaxSize:
        Ref: NumberOfEC2Instances
      DesiredCapacity:
        Ref: NumberOfEC2Instances
      Tags:
        - Key: Name
          Value: !Ref InstanceNames
          PropagateAtLaunch: 'true'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: 'true'

  ContainerInstances:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId:
        Fn::FindInMap:
        - AWSAMIRegionMap
        - Ref: AWS::Region
        - Ref: InstanceAMICode
      SecurityGroups:
        - Ref: EC2SecurityGroup
      InstanceType:
        Ref: EC2InstanceType
      KeyName:
        Ref: EC2KeyPairName
      IamInstanceProfile:
        Ref: EC2InstanceProfileArn
      UserData:
        Fn::Base64:
          Fn::Join:
          - ''
          - - "#!/bin/bash -x"
            - "\n"
            - "yum install -y aws-cfn-bootstrap"
            - "\n"
            - Ref: LaunchScriptText
            - "\n"
            - "res=$?"
            - "\n"
            - "echo $res"
            - "\n"
            - "/opt/aws/bin/cfn-signal -e $res "
            - "         --stack "
            - Ref: AWS::StackName
            - "         --resource ServiceAutoScalingGroup "
            - "         --region "
            - Ref: AWS::Region
            - "\n"
